import React from 'react';

const str = 'This app was built with create-react-app.\nAll fonts generated by Google Font API.\n-----\n'

class Info extends React.Component {
	getLinkString() {
		if (typeof this.props.value !== 'undefined') {
			return `<link rel="stylesheet" href=${this.props.value}>`
		}
		return '';
	}
	render() {
		return(
			<div className="info">
				<textarea value={str + this.getLinkString()} readOnly></textarea>
			</div>
		)
	}
}

export default Info;